/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import java.awt.Toolkit;
import java.util.TooManyListenersException;

/**
 *
 * @author angel
 */
public class Calculador_Principal extends javax.swing.JFrame {

    public float Num_primero;
    public float Num_segundo;
    public String operador;
    
    public Calculador_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Fuente = new javax.swing.JPanel();
        Casilla = new javax.swing.JLabel();
        Potencia = new javax.swing.JButton();
        Divicion = new javax.swing.JButton();
        Procentaje = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        Num_0 = new javax.swing.JButton();
        Punto_Decimal = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Num_3 = new javax.swing.JButton();
        Num_6 = new javax.swing.JButton();
        Num_9 = new javax.swing.JButton();
        Num_2 = new javax.swing.JButton();
        Num_5 = new javax.swing.JButton();
        Num_8 = new javax.swing.JButton();
        Num_4 = new javax.swing.JButton();
        Num_7 = new javax.swing.JButton();
        Num_1 = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fuente.setMinimumSize(new java.awt.Dimension(400, 600));
        Fuente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Casilla.setBackground(new java.awt.Color(253, 238, 228));
        Casilla.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Casilla.setForeground(new java.awt.Color(149, 65, 47));
        Casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Casilla.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Casilla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(254, 245, 237), new java.awt.Color(254, 245, 237)));
        Casilla.setOpaque(true);
        Fuente.add(Casilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 310, 120));

        Potencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\potencia.png")); // NOI18N
        Potencia.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\potencia.png")); // NOI18N
        Potencia.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\potencia_1.png")); // NOI18N
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });
        Fuente.add(Potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, 70));

        Divicion.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Divicion.png")); // NOI18N
        Divicion.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Divicion.png")); // NOI18N
        Divicion.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Divicion_1.png")); // NOI18N
        Divicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivicionActionPerformed(evt);
            }
        });
        Fuente.add(Divicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, 70));

        Procentaje.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\%.png")); // NOI18N
        Procentaje.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\%.png")); // NOI18N
        Procentaje.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\%_1.png")); // NOI18N
        Procentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcentajeActionPerformed(evt);
            }
        });
        Fuente.add(Procentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 70, 70));

        Multiplicacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Multiplicacion.png")); // NOI18N
        Multiplicacion.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Multiplicacion.png")); // NOI18N
        Multiplicacion.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Multiplicacion_1.png")); // NOI18N
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });
        Fuente.add(Multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, 70));

        Num_0.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\0.png")); // NOI18N
        Num_0.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\0.png")); // NOI18N
        Num_0.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\0_0.png")); // NOI18N
        Num_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_0ActionPerformed(evt);
            }
        });
        Fuente.add(Num_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 70, 70));

        Punto_Decimal.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\punto.png")); // NOI18N
        Punto_Decimal.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\punto.png")); // NOI18N
        Punto_Decimal.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\punto_!.png")); // NOI18N
        Punto_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Punto_DecimalActionPerformed(evt);
            }
        });
        Fuente.add(Punto_Decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 70, 70));

        Igual.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\igual.png")); // NOI18N
        Igual.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\igual.png")); // NOI18N
        Igual.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\igual_1.png")); // NOI18N
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });
        Fuente.add(Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 150, 70));

        Suma.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Suma.png")); // NOI18N
        Suma.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Suma.png")); // NOI18N
        Suma.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\Suma_1.png")); // NOI18N
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });
        Fuente.add(Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 70, 70));

        Resta.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\menos.png")); // NOI18N
        Resta.setBorder(null);
        Resta.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\menos.png")); // NOI18N
        Resta.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\resta_!.png")); // NOI18N
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });
        Fuente.add(Resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        Num_3.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\3.png")); // NOI18N
        Num_3.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\3.png")); // NOI18N
        Num_3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\3_1.png")); // NOI18N
        Num_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_3ActionPerformed(evt);
            }
        });
        Fuente.add(Num_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 70, 70));

        Num_6.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\6.png")); // NOI18N
        Num_6.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\6.png")); // NOI18N
        Num_6.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\6_!.png")); // NOI18N
        Num_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_6ActionPerformed(evt);
            }
        });
        Fuente.add(Num_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 70, 70));

        Num_9.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\9.png")); // NOI18N
        Num_9.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\9.png")); // NOI18N
        Num_9.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\9_1.png")); // NOI18N
        Num_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_9ActionPerformed(evt);
            }
        });
        Fuente.add(Num_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 70, 70));

        Num_2.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\2.png")); // NOI18N
        Num_2.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\2.png")); // NOI18N
        Num_2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\2_1.png")); // NOI18N
        Num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_2ActionPerformed(evt);
            }
        });
        Fuente.add(Num_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 70));

        Num_5.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\5.png")); // NOI18N
        Num_5.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\5.png")); // NOI18N
        Num_5.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\5_1.png")); // NOI18N
        Num_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_5ActionPerformed(evt);
            }
        });
        Fuente.add(Num_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, 70));

        Num_8.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\8.png")); // NOI18N
        Num_8.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\8.png")); // NOI18N
        Num_8.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\8_!.png")); // NOI18N
        Num_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_8ActionPerformed(evt);
            }
        });
        Fuente.add(Num_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, 70));

        Num_4.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\4.png")); // NOI18N
        Num_4.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\4.png")); // NOI18N
        Num_4.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\4_!.png")); // NOI18N
        Num_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_4ActionPerformed(evt);
            }
        });
        Fuente.add(Num_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 70, 70));

        Num_7.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\7.png")); // NOI18N
        Num_7.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\7.png")); // NOI18N
        Num_7.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\7_1.png")); // NOI18N
        Num_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_7ActionPerformed(evt);
            }
        });
        Fuente.add(Num_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 70));

        Num_1.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\1.png")); // NOI18N
        Num_1.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\1.png")); // NOI18N
        Num_1.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\1.png")); // NOI18N
        Num_1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\1)_1.png")); // NOI18N
        Num_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_1ActionPerformed(evt);
            }
        });
        Fuente.add(Num_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 70, 70));

        AC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculadora/AC.png"))); // NOI18N
        AC.setBorder(null);
        AC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AC.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\AC.png")); // NOI18N
        AC.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Desktop\\Monkey_Calculadora\\Imagenes\\AC_1.png")); // NOI18N
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });
        Fuente.add(AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 70));

        Fondo.setBackground(new java.awt.Color(254, 234, 219));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculadora/Fondo.jpg"))); // NOI18N
        Fondo.setOpaque(true);
        Fuente.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcentajeActionPerformed
             this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="%";
        this.Casilla.setText("");
    }//GEN-LAST:event_ProcentajeActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
         this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="*";
        this.Casilla.setText("");
    }//GEN-LAST:event_MultiplicacionActionPerformed

    private void Num_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_3ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"3");
    }//GEN-LAST:event_Num_3ActionPerformed

    private void Num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_2ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"2");
    }//GEN-LAST:event_Num_2ActionPerformed

    private void Num_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_0ActionPerformed
       
        this.Casilla.setText(this.Casilla.getText()+"0");
        
    }//GEN-LAST:event_Num_0ActionPerformed

    private void Num_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_1ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"1");
    }//GEN-LAST:event_Num_1ActionPerformed

    private void Num_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_6ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"6");
    }//GEN-LAST:event_Num_6ActionPerformed

    private void Num_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_5ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"5");
    }//GEN-LAST:event_Num_5ActionPerformed

    private void Num_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_4ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"4");
    }//GEN-LAST:event_Num_4ActionPerformed

    private void Num_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_7ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"7");
    }//GEN-LAST:event_Num_7ActionPerformed

    private void Num_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_8ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"8");
    }//GEN-LAST:event_Num_8ActionPerformed

    private void Num_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_9ActionPerformed
       this.Casilla.setText(this.Casilla.getText()+"9");
    }//GEN-LAST:event_Num_9ActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        this.Casilla.setText("");
    }//GEN-LAST:event_ACActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="+";
        //""+Num_primero+"+"
        this.Casilla.setText("");
    }//GEN-LAST:event_SumaActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        this.Num_segundo=Float.parseFloat(this.Casilla.getText());
        
        switch(this.operador){
            case "+":this.Casilla.setText(sincero(this.Num_primero+this.Num_segundo));break;
            case "-":this.Casilla.setText(sincero(this.Num_primero-this.Num_segundo));break;
            case "/":this.Casilla.setText(sincero(this.Num_primero/this.Num_segundo));break;
            case "^":this.Casilla.setText(sincero((float) Math.pow(this.Num_primero, this.Num_segundo)));break;
            case "*":if (this.Num_segundo==0){this.Casilla.setText("NoSeDivideEntrecero");}
            else{
                this.Casilla.setText(sincero(this.Num_primero*this.Num_segundo));break;
            }
                case "%":this.Casilla.setText(sincero(this.Num_primero%this.Num_segundo));break;
        }
        
    }//GEN-LAST:event_IgualActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
         this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="-";
        this.Casilla.setText("");
    }//GEN-LAST:event_RestaActionPerformed

    private void DivicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivicionActionPerformed
         this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="/";
        this.Casilla.setText("");
    }//GEN-LAST:event_DivicionActionPerformed

    private void Punto_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Punto_DecimalActionPerformed
        if (!(this.Casilla.getText().contains("."))) {
            this.Casilla.setText(this.Casilla.getText()+".");
            
        }
    }//GEN-LAST:event_Punto_DecimalActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        this.Num_primero=Float.parseFloat(this.Casilla.getText());
        this.operador="^";
        this.Casilla.setText("");
    }//GEN-LAST:event_PotenciaActionPerformed

   
     public String sincero(float resultado){
         String retorno="";
         retorno=Float.toString(resultado);
         
         if(resultado%1==0){
             retorno=retorno.substring(0, retorno. length() -2);
         }
         
         return retorno;
     }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculador_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculador_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculador_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculador_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculador_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JLabel Casilla;
    private javax.swing.JButton Divicion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Fuente;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton Num_0;
    private javax.swing.JButton Num_1;
    private javax.swing.JButton Num_2;
    private javax.swing.JButton Num_3;
    private javax.swing.JButton Num_4;
    private javax.swing.JButton Num_5;
    private javax.swing.JButton Num_6;
    private javax.swing.JButton Num_7;
    private javax.swing.JButton Num_8;
    private javax.swing.JButton Num_9;
    private javax.swing.JButton Potencia;
    private javax.swing.JButton Procentaje;
    private javax.swing.JButton Punto_Decimal;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Suma;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
